### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by sinteary** [AY2122S1-CS2113T-T09-3/tp#114]
1. Not sure if you should include the overarching box `IngredientList` since it does not really fit into a class diagram.
From your description and my understanding of the code, `Parser` doesn't seem to maintain a reference to any `Command`s, so the line connecting them should be a dependency (dotted line arrow) rather than an association.
![image](https://user-images.githubusercontent.com/42560942/139184463-cdbbe5dc-ebd0-44ce-bbcb-0c2e4f92f40d.png)
2. This class diagram here seems to have missing navigability arrowheads between `IngredientGroup` and is associated classes `Ingredient` and `IngredientList`
![image](https://user-images.githubusercontent.com/42560942/139170339-86a317e5-a1ee-402a-88c7-d401e68d8c1e.png)

**Comment by mudkip8** [comment]
Arrowheads have been added
