### ISSUE TITLE
[PE-D] Total amount is 0 but doesn't get removed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-3/tp#152]
![image.png](https://raw.githubusercontent.com/teoziyiivy/ped/main/files/b68cfe0a-fb1c-43b4-9d17-785d33ba50cf.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: teoziyiivy/ped#6

**Comment by datn02** [comment]
WHAT IS THIS?? HOW CAN I REPLICATE THIS BUG??? WHAT'S THE MEANING OF LIFE??? HELLO???

**Comment by mudkip8** [comment]
This one i probably because we printed to 1dp

so a 0.02 kg means 0.0 printed
